name: Am I Owal
on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib requests
    - name: Generate development pattern
      run: |
        python - <<EOF
        import matplotlib.pyplot as plt
        import requests
        from datetime import datetime
        # GitHub API 호출 (사용자 활동 데이터를 가져옴)
        username = "mmingoo"  # 여기에 GitHub 사용자 이름을 넣어주세요
        response = requests.get(f"https://api.github.com/users/{username}/events")
        events = response.json()
        # 데이터 처리 및 시각화
        times = [datetime.strptime(event["created_at"], "%Y-%m-%dT%H:%M:%SZ").hour for event in events]
        plt.hist(times, bins=24, range=(0,24))
        plt.xlabel('Hour of the Day')
        plt.ylabel('Number of Events')
        plt.title('GitHub Activity by Hour')
        plt.savefig('owal_stats.svg')
        EOF
    - name: Commit results
      env:
        PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://${PAT}@github.com/${GITHUB_REPOSITORY}.git
        git add owal_stats.svg
        git commit -m 'Update GitHub activity pattern'
        git push
